-- Modulo Saude: perfis familiares e linha do tempo de medidas corporais.
-- Dependencias: 20260913_create_saude_module.sql e public.touch_updated_at().

begin;

create table if not exists public.tb_saude_perfis (
  id bigint generated by default as identity primary key,
  created_by uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  sexo text not null,
  data_nascimento date not null,
  peso_kg numeric(6,2) not null,
  altura_cm numeric(6,2) not null,
  cintura_cm numeric(6,2),
  quadril_cm numeric(6,2),
  peito_cm numeric(6,2),
  braco_cm numeric(6,2),
  coxa_cm numeric(6,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_perfis_nome_check check (char_length(trim(nome)) between 1 and 120),
  constraint tb_saude_perfis_sexo_check check (sexo in ('feminino', 'masculino', 'outro', 'nao_informado')),
  constraint tb_saude_perfis_data_nascimento_check check (data_nascimento >= date '1900-01-01' and data_nascimento <= current_date),
  constraint tb_saude_perfis_peso_check check (peso_kg between 1 and 500),
  constraint tb_saude_perfis_altura_check check (altura_cm between 30 and 260),
  constraint tb_saude_perfis_cintura_check check (cintura_cm is null or cintura_cm between 10 and 400),
  constraint tb_saude_perfis_quadril_check check (quadril_cm is null or quadril_cm between 10 and 400),
  constraint tb_saude_perfis_peito_check check (peito_cm is null or peito_cm between 10 and 400),
  constraint tb_saude_perfis_braco_check check (braco_cm is null or braco_cm between 5 and 200),
  constraint tb_saude_perfis_coxa_check check (coxa_cm is null or coxa_cm between 5 and 250)
);

create table if not exists public.tb_saude_perfil_medidas (
  id bigint generated by default as identity primary key,
  perfil_id bigint not null references public.tb_saude_perfis(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  peso_kg numeric(6,2) not null,
  altura_cm numeric(6,2) not null,
  cintura_cm numeric(6,2),
  quadril_cm numeric(6,2),
  peito_cm numeric(6,2),
  braco_cm numeric(6,2),
  coxa_cm numeric(6,2),
  imc numeric(5,2) generated always as (round(peso_kg / power(altura_cm / 100, 2), 2)) stored,
  registrado_em timestamptz not null default now()
);

create index if not exists tb_saude_perfil_medidas_perfil_tempo_idx
  on public.tb_saude_perfil_medidas (perfil_id, registrado_em desc);

create or replace function public.registrar_saude_perfil_medidas()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' or
     (new.peso_kg, new.altura_cm, new.cintura_cm, new.quadril_cm, new.peito_cm, new.braco_cm, new.coxa_cm)
       is distinct from
     (old.peso_kg, old.altura_cm, old.cintura_cm, old.quadril_cm, old.peito_cm, old.braco_cm, old.coxa_cm) then
    insert into public.tb_saude_perfil_medidas (
      perfil_id, created_by, peso_kg, altura_cm, cintura_cm, quadril_cm, peito_cm, braco_cm, coxa_cm
    ) values (
      new.id, new.created_by, new.peso_kg, new.altura_cm, new.cintura_cm, new.quadril_cm, new.peito_cm, new.braco_cm, new.coxa_cm
    );
  end if;
  return new;
end;
$$;

drop trigger if exists tb_saude_perfis_registrar_medidas on public.tb_saude_perfis;
create trigger tb_saude_perfis_registrar_medidas
  after insert or update on public.tb_saude_perfis
  for each row execute function public.registrar_saude_perfil_medidas();

drop trigger if exists tb_saude_perfis_touch_updated_at on public.tb_saude_perfis;
create trigger tb_saude_perfis_touch_updated_at
  before update on public.tb_saude_perfis
  for each row execute function public.touch_updated_at();

alter table public.tb_saude_perfis enable row level security;
alter table public.tb_saude_perfis force row level security;
alter table public.tb_saude_perfil_medidas enable row level security;
alter table public.tb_saude_perfil_medidas force row level security;

revoke all on public.tb_saude_perfis, public.tb_saude_perfil_medidas from anon;
grant select, insert, update on public.tb_saude_perfis to authenticated;
grant select on public.tb_saude_perfil_medidas to authenticated;
grant usage, select on sequence public.tb_saude_perfis_id_seq, public.tb_saude_perfil_medidas_id_seq to authenticated;

drop policy if exists tb_saude_perfis_own_select on public.tb_saude_perfis;
create policy tb_saude_perfis_own_select on public.tb_saude_perfis
  for select to authenticated using (created_by = auth.uid());
drop policy if exists tb_saude_perfis_own_insert on public.tb_saude_perfis;
create policy tb_saude_perfis_own_insert on public.tb_saude_perfis
  for insert to authenticated with check (created_by = auth.uid());
drop policy if exists tb_saude_perfis_own_update on public.tb_saude_perfis;
create policy tb_saude_perfis_own_update on public.tb_saude_perfis
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists tb_saude_perfil_medidas_own_select on public.tb_saude_perfil_medidas;
create policy tb_saude_perfil_medidas_own_select on public.tb_saude_perfil_medidas
  for select to authenticated using (created_by = auth.uid());

commit;

-- Rollback manual (nao executar junto com a migration):
-- begin;
-- drop table if exists public.tb_saude_perfil_medidas;
-- drop table if exists public.tb_saude_perfis;
-- drop function if exists public.registrar_saude_perfil_medidas();
-- commit;
