-- Modulo Saude: meta e historico diario de consumo de agua.
-- Dependencias: 20260913_create_saude_module.sql e public.touch_updated_at().

begin;

create table if not exists public.tb_saude_agua_metas (
  created_by uuid primary key references auth.users(id) on delete cascade,
  meta_doses smallint not null check (meta_doses between 1 and 100),
  nome text not null check (char_length(trim(nome)) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tb_saude_agua_logs (
  id bigint generated by default as identity primary key,
  created_by uuid not null references auth.users(id) on delete cascade,
  data_local date not null,
  meta_doses smallint not null check (meta_doses between 1 and 100),
  realizado_doses smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_agua_logs_usuario_dia_key unique (created_by, data_local),
  constraint tb_saude_agua_logs_realizado_check
    check (realizado_doses between 0 and meta_doses)
);

create index if not exists idx_saude_agua_logs_usuario_data
  on public.tb_saude_agua_logs (created_by, data_local desc);

drop trigger if exists tb_saude_agua_metas_touch_updated_at on public.tb_saude_agua_metas;
create trigger tb_saude_agua_metas_touch_updated_at
  before update on public.tb_saude_agua_metas
  for each row execute function public.touch_updated_at();

drop trigger if exists tb_saude_agua_logs_touch_updated_at on public.tb_saude_agua_logs;
create trigger tb_saude_agua_logs_touch_updated_at
  before update on public.tb_saude_agua_logs
  for each row execute function public.touch_updated_at();

alter table public.tb_saude_agua_metas enable row level security;
alter table public.tb_saude_agua_metas force row level security;
alter table public.tb_saude_agua_logs enable row level security;
alter table public.tb_saude_agua_logs force row level security;

revoke all on public.tb_saude_agua_metas, public.tb_saude_agua_logs from anon;
grant select, insert, update on public.tb_saude_agua_metas to authenticated;
grant select, insert, update on public.tb_saude_agua_logs to authenticated;
grant usage, select on sequence public.tb_saude_agua_logs_id_seq to authenticated;

drop policy if exists tb_saude_agua_metas_own_select on public.tb_saude_agua_metas;
create policy tb_saude_agua_metas_own_select on public.tb_saude_agua_metas
  for select to authenticated using (created_by = auth.uid());

drop policy if exists tb_saude_agua_metas_own_insert on public.tb_saude_agua_metas;
create policy tb_saude_agua_metas_own_insert on public.tb_saude_agua_metas
  for insert to authenticated with check (created_by = auth.uid());

drop policy if exists tb_saude_agua_metas_own_update on public.tb_saude_agua_metas;
create policy tb_saude_agua_metas_own_update on public.tb_saude_agua_metas
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists tb_saude_agua_logs_own_select on public.tb_saude_agua_logs;
create policy tb_saude_agua_logs_own_select on public.tb_saude_agua_logs
  for select to authenticated using (created_by = auth.uid());

drop policy if exists tb_saude_agua_logs_own_insert on public.tb_saude_agua_logs;
create policy tb_saude_agua_logs_own_insert on public.tb_saude_agua_logs
  for insert to authenticated with check (created_by = auth.uid());

drop policy if exists tb_saude_agua_logs_own_update on public.tb_saude_agua_logs;
create policy tb_saude_agua_logs_own_update on public.tb_saude_agua_logs
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

comment on table public.tb_saude_agua_metas is
  'Configuracao atual da meta diaria de doses de agua por usuario';
comment on table public.tb_saude_agua_logs is
  'Historico diario da meta e do consumo realizado de agua por usuario';

commit;
