-- Historico de check-ins finalizados no modulo de treino.
-- Rode este arquivo no SQL Editor do Supabase antes de publicar a API correspondente.
-- Dependencias: tb_missoes_treino_perfis, tb_missoes_treino e public.is_app_admin().

begin;

do $$
begin
  if to_regclass('public.tb_missoes_treino_perfis') is null then
    raise exception 'Dependencia ausente: public.tb_missoes_treino_perfis. Aplique primeiro 20260812_add_missoes_treino_perfis.sql.';
  end if;
  if to_regclass('public.tb_missoes_treino') is null then
    raise exception 'Dependencia ausente: public.tb_missoes_treino. Aplique primeiro as migrations-base do modulo de treino.';
  end if;
  if to_regprocedure('public.is_app_admin()') is null then
    raise exception 'Dependencia ausente: public.is_app_admin(). Aplique primeiro 20260718_enable_rls_user_permissions.sql.';
  end if;
end $$;

create table if not exists public.tb_missoes_treino_logs (
  id bigint generated by default as identity primary key,
  perfil_id bigint not null references public.tb_missoes_treino_perfis(id) on delete cascade,
  missao_id uuid references public.tb_missoes_treino(id) on delete set null,
  treino_nome text not null,
  duracao_segundos integer not null,
  finalizado_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint tb_missoes_treino_logs_nome_check
    check (char_length(trim(treino_nome)) between 1 and 160),
  constraint tb_missoes_treino_logs_duracao_check
    check (duracao_segundos between 1 and 604800)
);

create index if not exists idx_missoes_treino_logs_perfil_finalizado
  on public.tb_missoes_treino_logs (perfil_id, finalizado_em desc);

alter table public.tb_missoes_treino_logs enable row level security;
alter table public.tb_missoes_treino_logs force row level security;

revoke all on public.tb_missoes_treino_logs from anon;
grant select, insert, delete on public.tb_missoes_treino_logs to authenticated;
revoke all on sequence public.tb_missoes_treino_logs_id_seq from anon;
grant usage, select on sequence public.tb_missoes_treino_logs_id_seq to authenticated;

drop policy if exists tb_missoes_treino_logs_admin_select on public.tb_missoes_treino_logs;
create policy tb_missoes_treino_logs_admin_select
  on public.tb_missoes_treino_logs for select to authenticated
  using (public.is_app_admin());

drop policy if exists tb_missoes_treino_logs_admin_insert on public.tb_missoes_treino_logs;
create policy tb_missoes_treino_logs_admin_insert
  on public.tb_missoes_treino_logs for insert to authenticated
  with check (public.is_app_admin());

drop policy if exists tb_missoes_treino_logs_admin_delete on public.tb_missoes_treino_logs;
create policy tb_missoes_treino_logs_admin_delete
  on public.tb_missoes_treino_logs for delete to authenticated
  using (public.is_app_admin());

comment on table public.tb_missoes_treino_logs is
  'Historico de sessoes finalizadas no modo treino';

commit;
