-- Modulo Saude: catalogo, permissoes e tabela nutricional.
-- Dependencias: migration 20260718_enable_rls_user_permissions.sql.
-- Execute antes de scripts/seed-saude-tabela-nutricional.sql.

begin;

insert into public.app_modules (app_id, label, beta_default)
values ('saude', 'Saude', false)
on conflict (app_id) do update
  set label = excluded.label,
      beta_default = excluded.beta_default;

insert into public.app_user_permissions (user_id, app_id, can_access)
select r.user_id, 'saude', true
from public.app_user_roles r
where r.role in ('owner', 'admin')
on conflict (user_id, app_id) do update
  set can_access = excluded.can_access,
      updated_at = now();

create table if not exists public.tb_saude_tabela_nutricional (
  id bigint generated by default as identity primary key,
  source_order integer not null,
  categoria text not null,
  protocolo text,
  item text not null,
  porcao_equivalente text not null,
  source_file text not null default 'tabelas nutricionais dieta.xlsx',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_tabela_nutricional_source_order_key unique (source_order),
  constraint tb_saude_tabela_nutricional_item_key unique (categoria, protocolo, item),
  constraint tb_saude_tabela_nutricional_source_order_check check (source_order > 0),
  constraint tb_saude_tabela_nutricional_categoria_check check (char_length(trim(categoria)) between 1 and 80),
  constraint tb_saude_tabela_nutricional_protocolo_check check (protocolo is null or protocolo in ('Perder Peso', 'Manutenção')),
  constraint tb_saude_tabela_nutricional_item_check check (char_length(trim(item)) between 1 and 200),
  constraint tb_saude_tabela_nutricional_porcao_check check (char_length(trim(porcao_equivalente)) between 1 and 2000)
);

-- Compatibilidade para bancos onde a primeira versao desta migration ja foi aplicada.
-- O campo protocolo permanece apenas para preservar o seed legado e nao participa dos novos cadastros.
alter table public.tb_saude_tabela_nutricional
  alter column protocolo drop not null;

alter table public.tb_saude_tabela_nutricional
  drop constraint if exists tb_saude_tabela_nutricional_protocolo_check;
alter table public.tb_saude_tabela_nutricional
  add constraint tb_saude_tabela_nutricional_protocolo_check
  check (protocolo is null or protocolo in ('Perder Peso', 'Manutenção'));

comment on table public.tb_saude_tabela_nutricional is
  'Itens e porcoes equivalentes da tabela nutricional do modulo Saude';
comment on column public.tb_saude_tabela_nutricional.source_order is
  'Ordem original consolidada das abas da planilha fonte';
comment on column public.tb_saude_tabela_nutricional.categoria is
  'Aba/categoria original da planilha nutricional';
comment on column public.tb_saude_tabela_nutricional.protocolo is
  'Campo legado da planilha fonte; novos cadastros utilizam valor nulo';
comment on column public.tb_saude_tabela_nutricional.porcao_equivalente is
  'Porcao equivalente ou opcoes, preservadas como texto da fonte';

drop trigger if exists tb_saude_tabela_nutricional_touch_updated_at
  on public.tb_saude_tabela_nutricional;
create trigger tb_saude_tabela_nutricional_touch_updated_at
  before update on public.tb_saude_tabela_nutricional
  for each row execute function public.touch_updated_at();

alter table public.tb_saude_tabela_nutricional enable row level security;
alter table public.tb_saude_tabela_nutricional force row level security;

revoke all on public.tb_saude_tabela_nutricional from anon;
grant select, insert, update, delete on public.tb_saude_tabela_nutricional to authenticated;

revoke all on sequence public.tb_saude_tabela_nutricional_id_seq from anon;
grant usage, select on sequence public.tb_saude_tabela_nutricional_id_seq to authenticated;

drop policy if exists tb_saude_tabela_nutricional_admin_select
  on public.tb_saude_tabela_nutricional;
create policy tb_saude_tabela_nutricional_admin_select
  on public.tb_saude_tabela_nutricional
  for select
  to authenticated
  using (public.is_app_admin());

drop policy if exists tb_saude_tabela_nutricional_admin_insert
  on public.tb_saude_tabela_nutricional;
create policy tb_saude_tabela_nutricional_admin_insert
  on public.tb_saude_tabela_nutricional
  for insert
  to authenticated
  with check (public.is_app_admin());

drop policy if exists tb_saude_tabela_nutricional_admin_update
  on public.tb_saude_tabela_nutricional;
create policy tb_saude_tabela_nutricional_admin_update
  on public.tb_saude_tabela_nutricional
  for update
  to authenticated
  using (public.is_app_admin())
  with check (public.is_app_admin());

drop policy if exists tb_saude_tabela_nutricional_admin_delete
  on public.tb_saude_tabela_nutricional;
create policy tb_saude_tabela_nutricional_admin_delete
  on public.tb_saude_tabela_nutricional
  for delete
  to authenticated
  using (public.is_app_admin());

commit;

-- Rollback manual (nao executar junto com a migration):
-- begin;
-- drop table if exists public.tb_saude_tabela_nutricional;
-- delete from public.app_user_permissions where app_id = 'saude';
-- delete from public.app_modules where app_id = 'saude';
-- commit;
