-- Reset completo do modulo Saude: remove tabelas legadas e recria schema unificado.
-- Consumo de agua referencia tb_saude_perfis (nao ha mais tb_saude_agua_perfis).
-- tb_saude_tabela_nutricional e removida e nao e recriada (modulo retirado da nova versao).
-- ATENCAO: apaga todos os dados das tabelas tb_saude_* existentes. Faca backup antes.
-- Dependencias: public.touch_updated_at(), public.is_app_admin(), auth.users.

begin;

drop table if exists public.tb_saude_agua_logs cascade;
drop table if exists public.tb_saude_agua_metas cascade;
drop table if exists public.tb_saude_agua_perfis cascade;
drop table if exists public.tb_saude_perfil_medidas cascade;
drop table if exists public.tb_saude_dietas cascade;
drop table if exists public.tb_saude_perfis cascade;
drop table if exists public.tb_saude_tabela_nutricional cascade;

drop function if exists public.registrar_saude_perfil_medidas();

insert into public.app_modules (app_id, label, beta_default)
values ('saude', 'Saude', false)
on conflict (app_id) do update
  set label = excluded.label,
      beta_default = excluded.beta_default;

insert into public.app_user_permissions (user_id, app_id, can_access)
select r.user_id, 'saude', true
from public.app_user_roles r
where r.role in ('owner', 'admin')
on conflict (user_id, app_id) do update
  set can_access = excluded.can_access,
      updated_at = now();

-- Perfis de saude (master: peso, IMC, agua, dietas)
create table public.tb_saude_perfis (
  id bigint generated by default as identity primary key,
  created_by uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  sexo text not null,
  data_nascimento date not null,
  peso_kg numeric(6,2) not null,
  altura_cm numeric(6,2) not null,
  data_medicao date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_perfis_id_usuario_key unique (id, created_by),
  constraint tb_saude_perfis_nome_check check (char_length(trim(nome)) between 1 and 120),
  constraint tb_saude_perfis_sexo_check check (sexo in ('feminino', 'masculino', 'outro', 'nao_informado')),
  constraint tb_saude_perfis_data_nascimento_check check (data_nascimento >= date '1900-01-01' and data_nascimento <= current_date),
  constraint tb_saude_perfis_peso_check check (peso_kg between 1 and 500),
  constraint tb_saude_perfis_altura_check check (altura_cm between 30 and 260)
);

comment on table public.tb_saude_perfis is
  'Perfis familiares do modulo Saude; agua e dietas referenciam este id';

create table public.tb_saude_perfil_medidas (
  id bigint generated by default as identity primary key,
  perfil_id bigint not null references public.tb_saude_perfis(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  peso_kg numeric(6,2) not null,
  altura_cm numeric(6,2) not null,
  imc numeric(5,2) generated always as (round(peso_kg / power(altura_cm / 100, 2), 2)) stored,
  registrado_em timestamptz not null default now()
);

create index tb_saude_perfil_medidas_perfil_tempo_idx
  on public.tb_saude_perfil_medidas (perfil_id, registrado_em desc);

create or replace function public.registrar_saude_perfil_medidas()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.tb_saude_perfil_medidas (
      perfil_id, created_by, peso_kg, altura_cm, registrado_em
    ) values (
      new.id, new.created_by, new.peso_kg, new.altura_cm, now()
    );
  elsif (new.peso_kg, new.altura_cm) is distinct from (old.peso_kg, old.altura_cm) then
    insert into public.tb_saude_perfil_medidas (
      perfil_id, created_by, peso_kg, altura_cm, registrado_em
    ) values (
      new.id, new.created_by, new.peso_kg, new.altura_cm, now()
    );
  elsif new.data_medicao is distinct from old.data_medicao then
    update public.tb_saude_perfil_medidas
    set registrado_em = (new.data_medicao + time '12:00') at time zone 'America/Sao_Paulo'
    where id = (
      select id
      from public.tb_saude_perfil_medidas
      where perfil_id = new.id and created_by = new.created_by
      order by id desc
      limit 1
    );
  end if;
  return new;
end;
$$;

create trigger tb_saude_perfis_registrar_medidas
  after insert or update on public.tb_saude_perfis
  for each row execute function public.registrar_saude_perfil_medidas();

-- Dietas por perfil
create table public.tb_saude_dietas (
  id bigint generated by default as identity primary key,
  slug text not null,
  titulo text not null,
  objetivo text not null,
  duracao_dias smallint not null,
  descricao text not null default '',
  orientacoes_gerais text not null default '',
  ritual_diario text not null default '',
  dias jsonb not null default '[]'::jsonb,
  refeicoes jsonb not null default '[]'::jsonb,
  observacoes text not null default '',
  perfil_id bigint references public.tb_saude_perfis(id) on delete cascade,
  source_file text not null default 'Cadastro manual',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_dietas_slug_key unique (slug),
  constraint tb_saude_dietas_slug_check check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint tb_saude_dietas_titulo_check check (char_length(trim(titulo)) between 1 and 160),
  constraint tb_saude_dietas_objetivo_check check (char_length(trim(objetivo)) between 1 and 120),
  constraint tb_saude_dietas_duracao_check check (duracao_dias between 1 and 31),
  constraint tb_saude_dietas_dias_array_check check (jsonb_typeof(dias) = 'array'),
  constraint tb_saude_dietas_refeicoes_array_check check (jsonb_typeof(refeicoes) = 'array'),
  constraint tb_saude_dietas_dias_quantidade_check check (jsonb_array_length(dias) = duracao_dias)
);

create index tb_saude_dietas_perfil_id_idx on public.tb_saude_dietas (perfil_id);

-- Consumo de agua (por perfil de saude)
create table public.tb_saude_agua_metas (
  created_by uuid not null references auth.users(id) on delete cascade,
  perfil_id bigint not null,
  nome text not null,
  meta_doses smallint not null,
  updated_at timestamptz not null default now(),
  constraint tb_saude_agua_metas_pkey primary key (created_by, perfil_id),
  constraint tb_saude_agua_metas_perfil_fkey
    foreign key (perfil_id, created_by)
    references public.tb_saude_perfis (id, created_by) on delete cascade,
  constraint tb_saude_agua_metas_nome_check check (char_length(trim(nome)) between 1 and 80),
  constraint tb_saude_agua_metas_doses_check check (meta_doses between 1 and 100)
);

create table public.tb_saude_agua_logs (
  id bigint generated by default as identity primary key,
  created_by uuid not null references auth.users(id) on delete cascade,
  perfil_id bigint not null,
  data_local date not null,
  meta_doses smallint not null,
  realizado_doses smallint not null default 0,
  updated_at timestamptz not null default now(),
  constraint tb_saude_agua_logs_usuario_perfil_dia_key unique (created_by, perfil_id, data_local),
  constraint tb_saude_agua_logs_perfil_fkey
    foreign key (perfil_id, created_by)
    references public.tb_saude_perfis (id, created_by) on delete cascade,
  constraint tb_saude_agua_logs_realizado_check check (realizado_doses between 0 and meta_doses)
);

create index idx_saude_agua_logs_usuario_perfil_data
  on public.tb_saude_agua_logs (created_by, perfil_id, data_local desc);

-- Triggers updated_at
create trigger tb_saude_perfis_touch_updated_at
  before update on public.tb_saude_perfis
  for each row execute function public.touch_updated_at();

create trigger tb_saude_dietas_touch_updated_at
  before update on public.tb_saude_dietas
  for each row execute function public.touch_updated_at();

create trigger tb_saude_agua_metas_touch_updated_at
  before update on public.tb_saude_agua_metas
  for each row execute function public.touch_updated_at();

create trigger tb_saude_agua_logs_touch_updated_at
  before update on public.tb_saude_agua_logs
  for each row execute function public.touch_updated_at();

-- RLS
alter table public.tb_saude_perfis enable row level security;
alter table public.tb_saude_perfis force row level security;
alter table public.tb_saude_perfil_medidas enable row level security;
alter table public.tb_saude_perfil_medidas force row level security;
alter table public.tb_saude_dietas enable row level security;
alter table public.tb_saude_dietas force row level security;
alter table public.tb_saude_agua_metas enable row level security;
alter table public.tb_saude_agua_metas force row level security;
alter table public.tb_saude_agua_logs enable row level security;
alter table public.tb_saude_agua_logs force row level security;

revoke all on public.tb_saude_perfis, public.tb_saude_perfil_medidas from anon;
revoke all on public.tb_saude_dietas from anon;
revoke all on public.tb_saude_agua_metas, public.tb_saude_agua_logs from anon;

grant select, insert, update on public.tb_saude_perfis to authenticated;
grant select, insert, update, delete on public.tb_saude_perfil_medidas to authenticated;
grant select, insert, update, delete on public.tb_saude_dietas to authenticated;
grant select, insert, update, delete on public.tb_saude_agua_metas to authenticated;
grant select, insert, update on public.tb_saude_agua_logs to authenticated;

grant usage, select on sequence public.tb_saude_perfis_id_seq to authenticated;
grant usage, select on sequence public.tb_saude_perfil_medidas_id_seq to authenticated;
grant usage, select on sequence public.tb_saude_dietas_id_seq to authenticated;
grant usage, select on sequence public.tb_saude_agua_logs_id_seq to authenticated;

-- Policies: perfis (usuario)
create policy tb_saude_perfis_own_select on public.tb_saude_perfis
  for select to authenticated using (created_by = auth.uid());
create policy tb_saude_perfis_own_insert on public.tb_saude_perfis
  for insert to authenticated with check (created_by = auth.uid());
create policy tb_saude_perfis_own_update on public.tb_saude_perfis
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

create policy tb_saude_perfil_medidas_own_select on public.tb_saude_perfil_medidas
  for select to authenticated using (created_by = auth.uid());
create policy tb_saude_perfil_medidas_own_insert on public.tb_saude_perfil_medidas
  for insert to authenticated with check (created_by = auth.uid());
create policy tb_saude_perfil_medidas_own_update on public.tb_saude_perfil_medidas
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());
create policy tb_saude_perfil_medidas_own_delete on public.tb_saude_perfil_medidas
  for delete to authenticated using (created_by = auth.uid());

-- Policies: dietas (dono ou admin)
create policy tb_saude_dietas_select on public.tb_saude_dietas
  for select to authenticated using (created_by = auth.uid() or public.is_app_admin());
create policy tb_saude_dietas_insert on public.tb_saude_dietas
  for insert to authenticated with check (created_by = auth.uid() or public.is_app_admin());
create policy tb_saude_dietas_update on public.tb_saude_dietas
  for update to authenticated using (created_by = auth.uid() or public.is_app_admin())
  with check (created_by = auth.uid() or public.is_app_admin());
create policy tb_saude_dietas_delete on public.tb_saude_dietas
  for delete to authenticated using (created_by = auth.uid() or public.is_app_admin());

-- Policies: agua (usuario, perfil proprio)
create policy tb_saude_agua_metas_own_select on public.tb_saude_agua_metas
  for select to authenticated using (created_by = auth.uid());
create policy tb_saude_agua_metas_own_insert on public.tb_saude_agua_metas
  for insert to authenticated with check (created_by = auth.uid());
create policy tb_saude_agua_metas_own_update on public.tb_saude_agua_metas
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());
create policy tb_saude_agua_metas_own_delete on public.tb_saude_agua_metas
  for delete to authenticated using (created_by = auth.uid());

create policy tb_saude_agua_logs_own_select on public.tb_saude_agua_logs
  for select to authenticated using (created_by = auth.uid());
create policy tb_saude_agua_logs_own_insert on public.tb_saude_agua_logs
  for insert to authenticated with check (created_by = auth.uid());
create policy tb_saude_agua_logs_own_update on public.tb_saude_agua_logs
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

comment on table public.tb_saude_agua_metas is
  'Meta diaria de consumo de agua por perfil de saude';
comment on table public.tb_saude_agua_logs is
  'Registro diario de doses de agua por perfil de saude';

commit;
