-- Catalogo compartilhado de alimentos e seed completo a partir da planilha entregue.
begin;

create table if not exists public.tb_saude_alimentos (
  id bigint generated by default as identity primary key,
  source_order integer not null unique check (source_order > 0),
  categoria text not null check (char_length(trim(categoria)) between 1 and 80),
  item text not null check (char_length(trim(item)) between 1 and 200),
  porcao_equivalente text not null check (char_length(trim(porcao_equivalente)) between 1 and 200),
  peso_referencia_g numeric(10,2) check (peso_referencia_g is null or peso_referencia_g between 0.01 and 10000),
  kcal_100g numeric(10,2) not null check (kcal_100g between 0 and 2000),
  proteina_100g numeric(10,2) not null check (proteina_100g between 0 and 1000),
  carboidrato_100g numeric(10,2) not null check (carboidrato_100g between 0 and 1000),
  gordura_100g numeric(10,2) not null check (gordura_100g between 0 and 1000),
  observacoes text,
  fonte_nutricional text not null default 'Cadastro manual',
  source_file text not null default 'Cadastro manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tb_saude_alimentos_item_normalizado_key
  on public.tb_saude_alimentos (lower(trim(item)));
create index if not exists tb_saude_alimentos_categoria_order_idx
  on public.tb_saude_alimentos (categoria, source_order);

drop trigger if exists tb_saude_alimentos_touch_updated_at on public.tb_saude_alimentos;
create trigger tb_saude_alimentos_touch_updated_at
  before update on public.tb_saude_alimentos
  for each row execute function public.touch_updated_at();

alter table public.tb_saude_alimentos enable row level security;
alter table public.tb_saude_alimentos force row level security;
revoke all on public.tb_saude_alimentos from anon;
grant select, insert, update, delete on public.tb_saude_alimentos to authenticated;
grant usage, select on sequence public.tb_saude_alimentos_id_seq to authenticated;

drop policy if exists tb_saude_alimentos_select on public.tb_saude_alimentos;
create policy tb_saude_alimentos_select on public.tb_saude_alimentos
  for select to authenticated using (true);
drop policy if exists tb_saude_alimentos_insert on public.tb_saude_alimentos;
create policy tb_saude_alimentos_insert on public.tb_saude_alimentos
  for insert to authenticated with check (public.is_app_admin());
drop policy if exists tb_saude_alimentos_update on public.tb_saude_alimentos;
create policy tb_saude_alimentos_update on public.tb_saude_alimentos
  for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
drop policy if exists tb_saude_alimentos_delete on public.tb_saude_alimentos;
create policy tb_saude_alimentos_delete on public.tb_saude_alimentos
  for delete to authenticated using (public.is_app_admin());

insert into public.tb_saude_alimentos (
  source_order, categoria, item, porcao_equivalente, peso_referencia_g,
  kcal_100g, proteina_100g, carboidrato_100g, gordura_100g, observacoes, fonte_nutricional, source_file
) values
  (1, 'Proteínas', 'Peito de frango grelhado', '100 g', 100.0, 165.0, 31.0, 0.0, 3.6, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (2, 'Proteínas', 'Coxa/sobrecoxa de frango sem pele', '90 g', 90.0, 209.0, 26.0, 0.0, 10.9, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (3, 'Proteínas', 'Peru grelhado', '100 g', 100.0, 135.0, 29.0, 0.0, 1.6, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (4, 'Proteínas', 'Tilápia grelhada', '120 g', 120.0, 128.0, 26.0, 0.0, 2.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (5, 'Proteínas', 'Merluza cozida/grelhada', '120 g', 120.0, 111.0, 23.0, 0.0, 1.8, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (6, 'Proteínas', 'Salmão grelhado', '75 g (70–80 g)', 75.0, 206.0, 22.0, 0.0, 12.4, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (7, 'Proteínas', 'Sardinha grelhada', '90 g', 90.0, 208.0, 25.0, 0.0, 11.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (8, 'Proteínas', 'Atum em lata em água', '120 g', 120.0, 116.0, 25.5, 0.0, 0.8, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (9, 'Proteínas', 'Camarão cozido', '120 g', 120.0, 99.0, 24.0, 0.2, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (10, 'Proteínas', 'Ovo inteiro', '2 un (~100 g)', 100.0, 143.0, 12.6, 0.7, 9.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (11, 'Proteínas', 'Clara de ovo', '6 un (~198 g)', 198.0, 52.0, 10.9, 0.7, 0.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (12, 'Proteínas', 'Lombo suíno magro', '90 g', 90.0, 196.0, 29.0, 0.0, 8.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (13, 'Proteínas', 'Tofu firme grelhado', '120 g', 120.0, 144.0, 17.3, 2.8, 8.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (14, 'Proteínas', 'Bacon', '30 g', 30.0, 541.0, 37.0, 1.4, 42.0, 'Varia muito por marca e preparo.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (15, 'Carboidratos complexos', 'Arroz integral cozido', '120 g', 120.0, 123.0, 2.7, 25.6, 1.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (16, 'Carboidratos complexos', 'Batata-doce cozida', '120 g', 120.0, 76.0, 1.4, 17.7, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (17, 'Carboidratos complexos', 'Batata inglesa cozida', '120 g', 120.0, 87.0, 1.9, 20.1, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (18, 'Carboidratos complexos', 'Inhame cozido', '100 g', 100.0, 116.0, 1.5, 27.5, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (19, 'Carboidratos complexos', 'Mandioca cozida', '90 g', 90.0, 125.0, 0.6, 30.1, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (20, 'Carboidratos complexos', 'Mandioquinha cozida', '100 g', 100.0, 80.0, 0.9, 18.9, 0.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (21, 'Carboidratos complexos', 'Abóbora cabotiá cozida', '200 g', 200.0, 48.0, 1.4, 10.8, 0.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (22, 'Carboidratos complexos', 'Quinoa cozida', '90 g', 90.0, 120.0, 4.4, 21.3, 1.9, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (23, 'Carboidratos complexos', 'Aveia em flocos crua', '30 g', 30.0, 389.0, 16.9, 66.3, 6.9, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (24, 'Carboidratos complexos', 'Macarrão integral cozido', '90 g', 90.0, 149.0, 5.8, 30.1, 1.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (25, 'Carboidratos complexos', 'Cuscuz de milho cozido', '40 g', 40.0, 112.0, 2.2, 23.2, 0.7, 'O PDF agrupa cuscuz/tapioca; aqui estão separados.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (26, 'Carboidratos complexos', 'Tapioca preparada', '40 g', 40.0, 230.0, 0.2, 56.0, 0.1, 'Pode variar bastante conforme hidratação e marca.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (27, 'Carboidratos complexos', 'Feijão cozido', '100 g', 100.0, 76.0, 4.8, 13.6, 0.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (28, 'Carboidratos complexos', 'Lentilha cozida', '100 g', 100.0, 116.0, 9.0, 20.1, 0.4, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (29, 'Carboidratos complexos', 'Grão-de-bico cozido', '100 g', 100.0, 164.0, 8.9, 27.4, 2.6, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (30, 'Frutas', 'Morango', '200 g', 200.0, 32.0, 0.7, 7.7, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (31, 'Frutas', 'Melancia', '200 g', 200.0, 30.0, 0.6, 7.6, 0.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (32, 'Frutas', 'Melão', '200 g', 200.0, 34.0, 0.8, 8.2, 0.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (33, 'Frutas', 'Abacaxi', '140 g', 140.0, 50.0, 0.5, 13.1, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (34, 'Frutas', 'Maçã com casca', '130 g', 130.0, 52.0, 0.3, 13.8, 0.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (35, 'Frutas', 'Pera', '120 g', 120.0, 57.0, 0.4, 15.2, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (36, 'Frutas', 'Mamão papaia', '160 g', 160.0, 43.0, 0.5, 10.8, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (37, 'Frutas', 'Banana', '80 g', 80.0, 89.0, 1.1, 22.8, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (38, 'Frutas', 'Laranja', '120 g', 120.0, 47.0, 0.9, 11.8, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (39, 'Frutas', 'Tangerina', '130 g', 130.0, 53.0, 0.8, 13.3, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (40, 'Frutas', 'Kiwi', '110 g', 110.0, 61.0, 1.1, 14.7, 0.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (41, 'Frutas', 'Manga', '120 g', 120.0, 60.0, 0.8, 15.0, 0.4, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (42, 'Frutas', 'Pêssego', '130 g', 130.0, 39.0, 0.9, 9.5, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (43, 'Frutas', 'Ameixa fresca', '120 g', 120.0, 46.0, 0.7, 11.4, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (44, 'Frutas', 'Uva', '100 g', 100.0, 69.0, 0.7, 18.1, 0.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (45, 'Frutas', 'Frutas vermelhas (mix)', '150 g', 150.0, 43.0, 0.8, 10.0, 0.4, 'Mix genérico; composição muda conforme as frutas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (46, 'Frutas', 'Amora', '100 g (referência)', 100.0, 43.0, 1.4, 9.6, 0.5, 'Citada como exemplo de fruta vermelha.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (47, 'Frutas', 'Maracujá', '1 un (~50 g polpa)', 50.0, 97.0, 2.2, 23.4, 0.7, 'Porção aproximada de polpa.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (48, 'Frutas', 'Limão', '1 un (~58 g)', 58.0, 29.0, 1.1, 9.3, 0.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (49, 'Gorduras boas', 'Azeite extravirgem', '5 g (1 c. chá)', 5.0, 884.0, 0.0, 0.0, 100.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (50, 'Gorduras boas', 'Óleo de coco', '5 g', 5.0, 892.0, 0.0, 0.0, 100.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (51, 'Gorduras boas', 'Abacate', '30 g', 30.0, 160.0, 2.0, 8.5, 14.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (52, 'Gorduras boas', 'Castanha-do-Pará', '10 g (2 un)', 10.0, 659.0, 14.3, 11.7, 67.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (53, 'Gorduras boas', 'Castanha de caju', '12 g', 12.0, 553.0, 18.2, 30.2, 43.9, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (54, 'Gorduras boas', 'Amêndoas', '12 g', 12.0, 579.0, 21.2, 21.6, 49.9, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (55, 'Gorduras boas', 'Nozes', '10 g', 10.0, 654.0, 15.2, 13.7, 65.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (56, 'Gorduras boas', 'Avelã', '12 g', 12.0, 628.0, 15.0, 16.7, 60.8, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (57, 'Gorduras boas', 'Macadâmia', '10 g', 10.0, 718.0, 7.9, 13.8, 75.8, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (58, 'Gorduras boas', 'Pasta de amendoim integral', '15 g', 15.0, 588.0, 25.1, 20.0, 50.4, 'Sem açúcar adicionado; marcas variam.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (59, 'Gorduras boas', 'Sementes de chia', '10 g', 10.0, 486.0, 16.5, 42.1, 30.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (60, 'Gorduras boas', 'Sementes de linhaça', '10 g', 10.0, 534.0, 18.3, 28.9, 42.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (61, 'Gorduras boas', 'Sementes de girassol', '12 g', 12.0, 584.0, 20.8, 20.0, 51.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (62, 'Folhas verdes', 'Alface lisa', 'À vontade', null, 14.0, 1.4, 2.9, 0.2, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (63, 'Folhas verdes', 'Alface crespa', 'À vontade', null, 15.0, 1.4, 2.9, 0.2, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (64, 'Folhas verdes', 'Alface americana', 'À vontade', null, 14.0, 0.9, 3.0, 0.1, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (65, 'Folhas verdes', 'Alface roxa', 'À vontade', null, 15.0, 1.4, 2.9, 0.2, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (66, 'Folhas verdes', 'Rúcula', 'À vontade', null, 25.0, 2.6, 3.7, 0.7, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (67, 'Folhas verdes', 'Espinafre', 'À vontade', null, 23.0, 2.9, 3.6, 0.4, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (68, 'Folhas verdes', 'Agrião', 'À vontade', null, 11.0, 2.3, 1.3, 0.1, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (69, 'Folhas verdes', 'Couve', 'À vontade', null, 32.0, 3.0, 5.6, 0.6, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (70, 'Folhas verdes', 'Acelga', 'À vontade', null, 19.0, 1.8, 3.7, 0.2, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (71, 'Folhas verdes', 'Escarola', 'À vontade', null, 17.0, 1.3, 3.4, 0.2, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (72, 'Folhas verdes', 'Chicória', 'À vontade', null, 23.0, 1.7, 4.7, 0.3, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (73, 'Folhas verdes', 'Almeirão', 'À vontade', null, 23.0, 1.7, 4.7, 0.3, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (74, 'Folhas verdes', 'Bertalha', 'À vontade', null, 19.0, 1.8, 3.4, 0.3, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (75, 'Folhas verdes', 'Radicchio', 'À vontade', null, 23.0, 1.4, 4.5, 0.3, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (76, 'Folhas verdes', 'Folha de mostarda', 'À vontade', null, 27.0, 2.9, 4.7, 0.4, 'Valores por 100 g para comparação; o protocolo não fixa gramas.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (77, 'Legumes low-carb', 'Abobrinha', 'Até 200 g', 200.0, 17.0, 1.2, 3.1, 0.3, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (78, 'Legumes low-carb', 'Brócolis', 'Até 200 g', 200.0, 34.0, 2.8, 6.6, 0.4, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (79, 'Legumes low-carb', 'Couve-flor', 'Até 200 g', 200.0, 25.0, 1.9, 5.0, 0.3, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (80, 'Legumes low-carb', 'Berinjela', 'Até 200 g', 200.0, 25.0, 1.0, 5.9, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (81, 'Legumes low-carb', 'Chuchu', 'Até 200 g', 200.0, 19.0, 0.8, 4.5, 0.1, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (82, 'Legumes low-carb', 'Pepino', 'Até 200 g', 200.0, 15.0, 0.7, 3.6, 0.1, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (83, 'Legumes low-carb', 'Tomate', 'Até 200 g', 200.0, 18.0, 0.9, 3.9, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (84, 'Legumes low-carb', 'Pimentão verde', 'Até 200 g', 200.0, 20.0, 0.9, 4.6, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (85, 'Legumes low-carb', 'Pimentão vermelho', 'Até 200 g', 200.0, 31.0, 1.0, 6.0, 0.3, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (86, 'Legumes low-carb', 'Pimentão amarelo', 'Até 200 g', 200.0, 27.0, 1.0, 6.3, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (87, 'Legumes low-carb', 'Vagem', 'Até 200 g', 200.0, 31.0, 1.8, 7.0, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (88, 'Legumes low-carb', 'Quiabo', 'Até 200 g', 200.0, 33.0, 1.9, 7.5, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (89, 'Legumes low-carb', 'Jiló', 'Até 200 g', 200.0, 27.0, 1.4, 6.2, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (90, 'Legumes low-carb', 'Aspargos', 'Até 200 g', 200.0, 20.0, 2.2, 3.9, 0.1, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (91, 'Legumes low-carb', 'Rabanete', 'Até 200 g', 200.0, 16.0, 0.7, 3.4, 0.1, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (92, 'Legumes low-carb', 'Nabo', 'Até 200 g', 200.0, 28.0, 0.9, 6.4, 0.1, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (93, 'Legumes low-carb', 'Repolho verde', 'Até 200 g', 200.0, 25.0, 1.3, 5.8, 0.1, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (94, 'Legumes low-carb', 'Repolho roxo', 'Até 200 g', 200.0, 31.0, 1.4, 7.4, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (95, 'Legumes low-carb', 'Palmito', 'Até 200 g', 200.0, 36.0, 2.5, 4.6, 0.6, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (96, 'Legumes low-carb', 'Broto de bambu', 'Até 200 g', 200.0, 27.0, 2.6, 5.2, 0.3, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (97, 'Legumes low-carb', 'Cogumelos', 'Até 200 g', 200.0, 22.0, 3.1, 3.3, 0.3, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (98, 'Legumes low-carb', 'Alcachofra', 'Até 200 g', 200.0, 47.0, 3.3, 10.5, 0.2, 'Macros exibidos por 100 g; coluna de porção calcula 200 g.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (99, 'Temperos e extras', 'Alho', 'Livre / pequena quantidade', null, 149.0, 6.4, 33.1, 0.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (100, 'Temperos e extras', 'Cebola', 'Livre / pequena quantidade', null, 40.0, 1.1, 9.3, 0.1, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (101, 'Temperos e extras', 'Gengibre', 'Livre / pequena quantidade', null, 80.0, 1.8, 17.8, 0.8, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (102, 'Temperos e extras', 'Cúrcuma (açafrão-da-terra)', '1 c. chá (~3 g)', 3.0, 312.0, 9.7, 67.1, 3.3, 'Valor de cúrcuma em pó.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (103, 'Temperos e extras', 'Salsa', 'Livre', null, 36.0, 3.0, 6.3, 0.8, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (104, 'Temperos e extras', 'Cebolinha', 'Livre', null, 30.0, 3.3, 4.4, 0.7, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (105, 'Temperos e extras', 'Coentro', 'Livre', null, 23.0, 2.1, 3.7, 0.5, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (106, 'Temperos e extras', 'Manjericão', 'Livre', null, 23.0, 3.2, 2.7, 0.6, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (107, 'Temperos e extras', 'Orégano seco', 'Livre / pequena quantidade', null, 265.0, 9.0, 68.9, 4.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (108, 'Temperos e extras', 'Alecrim fresco', 'Livre / pequena quantidade', null, 131.0, 3.3, 20.7, 5.9, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (109, 'Temperos e extras', 'Pimenta-preta', 'Pitada', null, 251.0, 10.4, 64.0, 3.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (110, 'Temperos e extras', 'Pimenta caiena', 'Pitada', null, 318.0, 12.0, 56.6, 17.3, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (111, 'Temperos e extras', 'Canela em pó', 'Livre / pequena quantidade', null, 247.0, 4.0, 80.6, 1.2, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (112, 'Temperos e extras', 'Vinagre de maçã', '1 c. sobremesa (~10 g)', 10.0, 21.0, 0.0, 0.9, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (113, 'Temperos e extras', 'Sal integral', 'Pitada / livre conforme orientação', null, 0.0, 0.0, 0.0, 0.0, 'Sem macronutrientes; contém sódio.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (114, 'Temperos e extras', 'Stévia', 'A gosto', null, 0.0, 0.0, 0.0, 0.0, 'Considerada adoçante sem calorias na quantidade usual.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (115, 'Temperos e extras', 'Própolis verde', '20 gotas (~1 g)', 1.0, 250.0, 0.5, 60.0, 0.5, 'Estimativa genérica: composição varia muito por extrato/marca; conferir rótulo.', 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (116, 'Bebidas do protocolo', 'Chá verde sem açúcar', '1 xícara (~240 ml)', 240.0, 1.0, 0.2, 0.0, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (117, 'Bebidas do protocolo', 'Chá de hortelã sem açúcar', '1 xícara (~240 ml)', 240.0, 1.0, 0.0, 0.2, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (118, 'Bebidas do protocolo', 'Chá oolong sem açúcar', '1 xícara (~240 ml)', 240.0, 1.0, 0.0, 0.2, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (119, 'Bebidas do protocolo', 'Chá de cavalinha sem açúcar', '1 xícara (~240 ml)', 240.0, 1.0, 0.0, 0.2, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (120, 'Bebidas do protocolo', 'Chá de hibisco sem açúcar', '1 xícara (~240 ml)', 240.0, 1.0, 0.0, 0.2, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx'),
  (121, 'Bebidas do protocolo', 'Café sem açúcar', '1 xícara (~240 ml)', 240.0, 2.0, 0.1, 0.0, 0.0, null, 'TBCA/TACO; USDA FoodData Central (complementar)', 'tabela_nutricional_completa_protocolo_detox.xlsx')
on conflict (source_order) do update set
  categoria = excluded.categoria, item = excluded.item, porcao_equivalente = excluded.porcao_equivalente,
  peso_referencia_g = excluded.peso_referencia_g, kcal_100g = excluded.kcal_100g,
  proteina_100g = excluded.proteina_100g, carboidrato_100g = excluded.carboidrato_100g,
  gordura_100g = excluded.gordura_100g, observacoes = excluded.observacoes,
  fonte_nutricional = excluded.fonte_nutricional, source_file = excluded.source_file, updated_at = now();

commit;
