-- Modulo Saude: dietas estruturadas e seus planos diarios.
-- Dependencias: 20260913_create_saude_module.sql e public.touch_updated_at().

begin;

create table if not exists public.tb_saude_dietas (
  id bigint generated by default as identity primary key,
  slug text not null,
  titulo text not null,
  objetivo text not null,
  duracao_dias smallint not null,
  descricao text not null default '',
  orientacoes_gerais text not null default '',
  ritual_diario text not null default '',
  dias jsonb not null default '[]'::jsonb,
  observacoes text not null default '',
  source_file text not null default 'Cadastro manual',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_dietas_slug_key unique (slug),
  constraint tb_saude_dietas_slug_check check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint tb_saude_dietas_titulo_check check (char_length(trim(titulo)) between 1 and 160),
  constraint tb_saude_dietas_objetivo_check check (char_length(trim(objetivo)) between 1 and 120),
  constraint tb_saude_dietas_duracao_check check (duracao_dias between 1 and 31),
  constraint tb_saude_dietas_dias_array_check check (jsonb_typeof(dias) = 'array'),
  constraint tb_saude_dietas_dias_quantidade_check check (jsonb_array_length(dias) = duracao_dias)
);

comment on table public.tb_saude_dietas is
  'Dietas do modulo Saude, com orientacoes e plano diario estruturado em JSON';
comment on column public.tb_saude_dietas.dias is
  'Array JSON com numero, titulo, jejum_horas, quantidade_refeicoes, carboidrato e conteudo de cada dia';

drop trigger if exists tb_saude_dietas_touch_updated_at on public.tb_saude_dietas;
create trigger tb_saude_dietas_touch_updated_at
  before update on public.tb_saude_dietas
  for each row execute function public.touch_updated_at();

alter table public.tb_saude_dietas enable row level security;
alter table public.tb_saude_dietas force row level security;

revoke all on public.tb_saude_dietas from anon;
grant select, insert, update, delete on public.tb_saude_dietas to authenticated;

revoke all on sequence public.tb_saude_dietas_id_seq from anon;
grant usage, select on sequence public.tb_saude_dietas_id_seq to authenticated;

drop policy if exists tb_saude_dietas_admin_select on public.tb_saude_dietas;
create policy tb_saude_dietas_admin_select on public.tb_saude_dietas
  for select to authenticated using (public.is_app_admin());

drop policy if exists tb_saude_dietas_admin_insert on public.tb_saude_dietas;
create policy tb_saude_dietas_admin_insert on public.tb_saude_dietas
  for insert to authenticated with check (public.is_app_admin());

drop policy if exists tb_saude_dietas_admin_update on public.tb_saude_dietas;
create policy tb_saude_dietas_admin_update on public.tb_saude_dietas
  for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin());

drop policy if exists tb_saude_dietas_admin_delete on public.tb_saude_dietas;
create policy tb_saude_dietas_admin_delete on public.tb_saude_dietas
  for delete to authenticated using (public.is_app_admin());

commit;

-- Rollback manual (nao executar junto com a migration):
-- begin;
-- drop table if exists public.tb_saude_dietas;
-- commit;
