-- Perfis independentes para metas e historicos de consumo de agua.
-- Rode depois de 20260923_create_saude_consumo_agua.sql.

begin;

create table if not exists public.tb_saude_agua_perfis (
  id bigint generated by default as identity primary key,
  created_by uuid not null references auth.users(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tb_saude_agua_perfis_usuario_nome_key unique (created_by, nome),
  constraint tb_saude_agua_perfis_id_usuario_key unique (id, created_by)
);

drop trigger if exists tb_saude_agua_perfis_touch_updated_at on public.tb_saude_agua_perfis;
create trigger tb_saude_agua_perfis_touch_updated_at
  before update on public.tb_saude_agua_perfis
  for each row execute function public.touch_updated_at();

insert into public.tb_saude_agua_perfis (created_by, nome)
select usuarios.created_by, 'Meu perfil'
from (
  select created_by from public.tb_saude_agua_metas
  union
  select created_by from public.tb_saude_agua_logs
) as usuarios
on conflict (created_by, nome) do nothing;

alter table public.tb_saude_agua_metas add column if not exists perfil_id bigint;
alter table public.tb_saude_agua_logs add column if not exists perfil_id bigint;

update public.tb_saude_agua_metas as meta
set perfil_id = perfil.id
from public.tb_saude_agua_perfis as perfil
where meta.perfil_id is null and perfil.created_by = meta.created_by and perfil.nome = 'Meu perfil';

update public.tb_saude_agua_logs as log
set perfil_id = perfil.id
from public.tb_saude_agua_perfis as perfil
where log.perfil_id is null and perfil.created_by = log.created_by and perfil.nome = 'Meu perfil';

alter table public.tb_saude_agua_metas alter column perfil_id set not null;
alter table public.tb_saude_agua_logs alter column perfil_id set not null;

alter table public.tb_saude_agua_metas drop constraint if exists tb_saude_agua_metas_pkey;
alter table public.tb_saude_agua_metas
  add constraint tb_saude_agua_metas_pkey primary key (created_by, perfil_id);

alter table public.tb_saude_agua_logs drop constraint if exists tb_saude_agua_logs_usuario_dia_key;
alter table public.tb_saude_agua_logs
  add constraint tb_saude_agua_logs_usuario_perfil_dia_key unique (created_by, perfil_id, data_local);

alter table public.tb_saude_agua_metas drop constraint if exists tb_saude_agua_metas_perfil_usuario_fkey;
alter table public.tb_saude_agua_metas
  add constraint tb_saude_agua_metas_perfil_usuario_fkey
  foreign key (perfil_id, created_by)
  references public.tb_saude_agua_perfis (id, created_by) on delete cascade;

alter table public.tb_saude_agua_logs drop constraint if exists tb_saude_agua_logs_perfil_usuario_fkey;
alter table public.tb_saude_agua_logs
  add constraint tb_saude_agua_logs_perfil_usuario_fkey
  foreign key (perfil_id, created_by)
  references public.tb_saude_agua_perfis (id, created_by) on delete cascade;

drop index if exists public.idx_saude_agua_logs_usuario_data;
create index if not exists idx_saude_agua_logs_usuario_perfil_data
  on public.tb_saude_agua_logs (created_by, perfil_id, data_local desc);

alter table public.tb_saude_agua_perfis enable row level security;
alter table public.tb_saude_agua_perfis force row level security;
revoke all on public.tb_saude_agua_perfis from anon;
grant select, insert, update, delete on public.tb_saude_agua_perfis to authenticated;
grant usage, select on sequence public.tb_saude_agua_perfis_id_seq to authenticated;

drop policy if exists tb_saude_agua_perfis_own_select on public.tb_saude_agua_perfis;
create policy tb_saude_agua_perfis_own_select on public.tb_saude_agua_perfis
  for select to authenticated using (created_by = auth.uid());

drop policy if exists tb_saude_agua_perfis_own_insert on public.tb_saude_agua_perfis;
create policy tb_saude_agua_perfis_own_insert on public.tb_saude_agua_perfis
  for insert to authenticated with check (created_by = auth.uid());

drop policy if exists tb_saude_agua_perfis_own_update on public.tb_saude_agua_perfis;
create policy tb_saude_agua_perfis_own_update on public.tb_saude_agua_perfis
  for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists tb_saude_agua_perfis_own_delete on public.tb_saude_agua_perfis;
create policy tb_saude_agua_perfis_own_delete on public.tb_saude_agua_perfis
  for delete to authenticated using (created_by = auth.uid());

comment on table public.tb_saude_agua_perfis is
  'Perfis de pessoas com metas independentes de consumo de agua';

commit;
