import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { expect, it } from 'vitest';
import { DIET_WEEK, createEmptyDietMeals } from '../../features/saude/service/dietasService.js';
it('migration reaplicável, RPC atômica semanal e rollback sem perder dietas',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table tb_saude_perfis(id bigint primary key,created_by uuid);
 insert into tb_saude_perfis values(1,'f88a6351-317d-425b-afcd-9430c8a34f53');
 create table tb_saude_alimentos(id bigint generated by default as identity primary key,item text,categoria text,porcao_equivalente text,peso_referencia_g numeric,peso_unidade_g numeric,kcal_100g numeric,proteina_100g numeric,carboidrato_100g numeric,gordura_100g numeric,observacoes text,fonte_nutricional text);
 create table tb_saude_dietas(id bigint generated by default as identity primary key,slug text,titulo text,objetivo text,duracao_dias smallint,descricao text,orientacoes_gerais text,ritual_diario text,dias jsonb,refeicoes jsonb,observacoes text,meta_calorias integer,perfil_id bigint,source_file text,created_by uuid);
 insert into tb_saude_dietas(titulo,duracao_dias,refeicoes) values('Legada',1,'[]');`);
 const sql=await readFile(new URL('../../migration/20261010_add_saude_dietas_semanais.sql',import.meta.url),'utf8');
 await db.exec(sql);await db.exec(sql);
 expect((await db.query("select semanal,semana from tb_saude_dietas where titulo='Legada'")).rows[0]).toEqual({semanal:false,semana:[]});
 const semana=DIET_WEEK.map(titulo=>({titulo,refeicoes:createEmptyDietMeals()}));
 semana[4].refeicoes[2].itens.push({nome:'Teste SQL',quantidade:'100 g'});
 const diet={slug:'teste-sql',titulo:'Semanal SQL',objetivo:'Plano',duracao_dias:7,descricao:'',orientacoes_gerais:'',ritual_diario:'',dias:DIET_WEEK.map((titulo,index)=>({numero:index+1,titulo})),refeicoes:semana[4].refeicoes,semanal:true,semana,dia_edicao:4,observacoes:'',perfil_id:1};
 const food={item:'Teste SQL',categoria:'Outros',porcao:'100 g',peso_referencia_g:100,kcal_100g:100,proteina_100g:10,carboidrato_100g:10,gordura_100g:2};
 const call=(id)=>db.query("select save_saude_dieta_with_food($1,$2,true,$3::jsonb,$4::jsonb,'almoco',0) as result",[id,'f88a6351-317d-425b-afcd-9430c8a34f53',JSON.stringify(diet),JSON.stringify(food)]);
 const result=(await call(null)).rows[0].result;
 expect(result.row.semanal).toBe(true);expect(result.row.refeicoes).toEqual([]);
 expect(result.row.semana[4].refeicoes[2].itens[0].alimento_id).toBe(result.food.id);
 expect(result.row.semana[0].refeicoes[2].itens).toEqual([]);
 await call(result.row.id);expect((await db.query('select id from tb_saude_alimentos')).rows).toHaveLength(1);
 await expect(db.query("update tb_saude_dietas set semana='[]' where semanal")).rejects.toThrow();
 const rollback=await readFile(new URL('../../migration/rollback/20261010_saude_dietas_semanais.sql',import.meta.url),'utf8');
 await expect(db.exec(rollback)).rejects.toThrow(/Existem dietas semanais/);await db.exec('rollback');
 await db.query('delete from tb_saude_dietas where id=$1',[result.row.id]);await db.exec(rollback);
 expect((await db.query('select titulo from tb_saude_dietas')).rows[0].titulo).toBe('Legada');
 } finally {await db.close();}
},20000);
