-- Estado consolidado do modelo financeiro.
-- Cada ciclo de aprendizado do cron gera uma nova fotografia do motor.

CREATE TABLE IF NOT EXISTS public.tb_financeiro_modelo_estado (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_ano text NOT NULL,
  escopo text NOT NULL DEFAULT 'financeiro',
  origem text NOT NULL DEFAULT 'cron_aprendizado',
  run_id bigint NULL,
  feature_id bigint NULL,
  analysis_id bigint NULL,
  pesos jsonb NOT NULL DEFAULT '{}'::jsonb,
  feedback jsonb NOT NULL DEFAULT '{}'::jsonb,
  score_risco numeric(10, 2) NULL,
  risco_classificado text NULL,
  aprendizado_percentual numeric(10, 2) NOT NULL DEFAULT 0,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadados jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tb_financeiro_modelo_estado_mes_ano
  ON public.tb_financeiro_modelo_estado (mes_ano, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_tb_financeiro_modelo_estado_created_at
  ON public.tb_financeiro_modelo_estado (created_at DESC, id DESC);

ALTER TABLE public.tb_financeiro_modelo_estado
  ADD CONSTRAINT tb_financeiro_modelo_estado_aprendizado_check
  CHECK (aprendizado_percentual >= 0 AND aprendizado_percentual <= 100);

ALTER TABLE public.tb_financeiro_modelo_estado ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tb_financeiro_modelo_estado'
      AND policyname = 'service_role_full_access_tb_financeiro_modelo_estado'
  ) THEN
    CREATE POLICY service_role_full_access_tb_financeiro_modelo_estado
      ON public.tb_financeiro_modelo_estado
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

