-- Historico bruto de execucoes do analista financeiro
-- Guarda cada recalculo da aba e cada ciclo real do cron para aprendizado futuro.

CREATE TABLE IF NOT EXISTS public.tb_financeiro_analise_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_ano text NOT NULL,
  escopo text NOT NULL DEFAULT 'financeiro',
  origem text NOT NULL DEFAULT 'consulta_aba',
  tipo_execucao text NOT NULL DEFAULT 'recalculo',
  allow_learning boolean NOT NULL DEFAULT false,
  feature_id bigint NULL,
  analysis_id bigint NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadados jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tb_financeiro_analise_runs_mes_ano
  ON public.tb_financeiro_analise_runs (mes_ano, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_tb_financeiro_analise_runs_created_at
  ON public.tb_financeiro_analise_runs (created_at DESC, id DESC);

ALTER TABLE public.tb_financeiro_analise_runs
  ADD CONSTRAINT tb_financeiro_analise_runs_tipo_execucao_check
  CHECK (tipo_execucao IN ('recalculo', 'aprendizado'));

ALTER TABLE public.tb_financeiro_analise_runs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tb_financeiro_analise_runs'
      AND policyname = 'service_role_full_access_tb_financeiro_analise_runs'
  ) THEN
    CREATE POLICY service_role_full_access_tb_financeiro_analise_runs
      ON public.tb_financeiro_analise_runs
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

