# Nome do processo no painel Actions do GitHub
name: Despertador do Super App

on:
  schedule:
    # Roda de hora em hora (Minuto 0)
    - cron: '0 * * * *'
  
  # Permite que você teste clicando num botão no GitHub
  workflow_dispatch:

jobs:
  acordar_vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Enviando o sinal para o Porteiro na Vercel
        run: |
          curl -X POST "https://super-app-zeta-virid.vercel.app/api/index" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"
